### ISSUE TITLE
Bug in Transactions

### ISSUE THREAD

**Issue by josephadah** [texyh/Nextekk_Training#1]
Here is a screenshot of the error i got when trying to checkout. 
![mompop error](https://user-images.githubusercontent.com/18199983/41499779-30ddce58-717e-11e8-87d4-793aa52360e9.png)

**Comment by texyh** [comment]
Run schema compare and update your database

**Comment by josephadah** [comment]
Yes, Running Schema compare and updating resolve the issue #1
